//add shapes textures
$('.tab-content[data-tab-index=0]').append(`
<div class="img-holder"><img src="texture_packs/shapes/circle.png"><p>circle</p></div>
<div class="img-holder"><img src="texture_packs/shapes/equal_triangle.png"><p>equal_trian...</p></div>
<div class="img-holder"><img src="texture_packs/shapes/gradient.png"><p>gradient</p></div>
<div class="img-holder"><img src="texture_packs/shapes/right_triangle.png"><p>right_trian...</p></div>
<div class="img-holder"><img src="texture_packs/shapes/rounded_square.png"><p>rounded_squ...</p></div>
<div class="img-holder"><img src="texture_packs/shapes/square.png"><p>square</p></div>
<div class="img-holder"><img src="texture_packs/shapes/star.png"><p>star</p></div>
`)

//add platformer_graphics_deluxe textures
$('.tab-content[data-tab-index=1]').append(`
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/blockerBody.png"><p>blockerBody</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/blockerMad.png"><p>blockerMad</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/blockerSad.png"><p>blockerSad</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/bomb.png"><p>bomb</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/bombFlash.png"><p>bombFlash</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/box.png"><p>box</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxAlt.png"><p>boxAlt</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxCoin.png"><p>boxCoin</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxCoin_disabled.png"><p>boxCoin_dis...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxCoinAlt.png"><p>boxCoinAlt</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxCoinAlt_disabled.png"><p>boxCoinAlt_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxEmpty.png"><p>boxEmpty</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxExplosive.png"><p>boxExplosiv...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxExplosive_disabled.png"><p>boxExplosiv...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxExplosiveAlt.png"><p>boxExplosiv...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxItem.png"><p>boxItem</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxItem_disabled.png"><p>boxItem_dis...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxItemAlt.png"><p>boxItemAlt</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxItemAlt_disabled.png"><p>boxItemAlt_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/boxWarning.png"><p>boxWarning</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/brickWall.png"><p>brickWall</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/bridge.png"><p>bridge</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/bridgeLogs.png"><p>bridgeLogs</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/bush.png"><p>bush</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonBlue.png"><p>buttonBlue</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonBlue_pressed.png"><p>buttonBlue_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonGreen.png"><p>buttonGreen</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonGreen_pressed.png"><p>buttonGreen...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonRed.png"><p>buttonRed</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonRed_pressed.png"><p>buttonRed_p...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonYellow.png"><p>buttonYello...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/buttonYellow_pressed.png"><p>buttonYello...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/cactus.png"><p>cactus</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castle.png"><p>castle</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCenter.png"><p>castleCente...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCenter_rounded.png"><p>castleCente...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCliffLeft.png"><p>castleCliff...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCliffLeftAlt.png"><p>castleCliff...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCliffRight.png"><p>castleCliff...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleCliffRightAlt.png"><p>castleCliff...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHalf.png"><p>castleHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHalfLeft.png"><p>castleHalfL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHalfMid.png"><p>castleHalfM...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHalfRight.png"><p>castleHalfR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHillLeft.png"><p>castleHillL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHillLeft2.png"><p>castleHillL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHillRight.png"><p>castleHillR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleHillRight2.png"><p>castleHillR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleLedgeLeft.png"><p>castleLedge...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleLedgeRight.png"><p>castleLedge...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleLeft.png"><p>castleLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleMid.png"><p>castleMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/castleRight.png"><p>castleRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/chain.png"><p>chain</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/cloud1.png"><p>cloud1</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/cloud2.png"><p>cloud2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/cloud3.png"><p>cloud3</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/coinBronze.png"><p>coinBronze</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/coinGold.png"><p>coinGold</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/coinSilver.png"><p>coinSilver</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirt.png"><p>dirt</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCenter.png"><p>dirtCenter</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCenter_rounded.png"><p>dirtCenter_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCliffLeft.png"><p>dirtCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCliffLeftAlt.png"><p>dirtCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCliffRight.png"><p>dirtCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtCliffRightAlt.png"><p>dirtCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHalf.png"><p>dirtHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHalfLeft.png"><p>dirtHalfLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHalfMid.png"><p>dirtHalfMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHalfRight.png"><p>dirtHalfRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHillLeft.png"><p>dirtHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHillLeft2.png"><p>dirtHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHillRight.png"><p>dirtHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtHillRight2.png"><p>dirtHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtLedgeLeft.png"><p>dirtLedgeLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtLedgeRight.png"><p>dirtLedgeRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtLeft.png"><p>dirtLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtMid.png"><p>dirtMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/dirtRight.png"><p>dirtRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/door_closedMid.png"><p>door_closed...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/door_closedTop.png"><p>door_closed...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/door_openMid.png"><p>door_openMi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/door_openTop.png"><p>door_openTo...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/fence.png"><p>fence</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/fenceBroken.png"><p>fenceBroken</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/fireball.png"><p>fireball</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/fish.png"><p>fish</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagBlue.png"><p>flagBlue</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagBlue2.png"><p>flagBlue2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagBlueHanging.png"><p>flagBlueHan...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagGreen.png"><p>flagGreen</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagGreen2.png"><p>flagGreen2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagGreenHanging.png"><p>flagGreenHa...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagRed.png"><p>flagRed</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagRed2.png"><p>flagRed2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagRedHanging.png"><p>flagRedHang...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagYellow.png"><p>flagYellow</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagYellow2.png"><p>flagYellow2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/flagYellowHanging.png"><p>flagYellowH...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/fly.png"><p>fly</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/gemBlue.png"><p>gemBlue</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/gemGreen.png"><p>gemGreen</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/gemRed.png"><p>gemRed</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/gemYellow.png"><p>gemYellow</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grass.png"><p>grass</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCenter.png"><p>grassCenter</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCenter_rounded.png"><p>grassCenter...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCliffLeft.png"><p>grassCliffL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCliffLeftAlt.png"><p>grassCliffL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCliffRight.png"><p>grassCliffR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassCliffRightAlt.png"><p>grassCliffR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHalf.png"><p>grassHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHalfLeft.png"><p>grassHalfLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHalfMid.png"><p>grassHalfMi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHalfRight.png"><p>grassHalfRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHillLeft.png"><p>grassHillLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHillLeft2.png"><p>grassHillLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHillRight.png"><p>grassHillRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassHillRight2.png"><p>grassHillRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassLedgeLeft.png"><p>grassLedgeL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassLedgeRight.png"><p>grassLedgeR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassLeft.png"><p>grassLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassMid.png"><p>grassMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/grassRight.png"><p>grassRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/hill_large.png"><p>hill_large</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/hill_largeAlt.png"><p>hill_largeA...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/hill_small.png"><p>hill_small</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/hill_smallAlt.png"><p>hill_smallA...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/keyBlue.png"><p>keyBlue</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/keyGreen.png"><p>keyGreen</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/keyRed.png"><p>keyRed</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/keyYellow.png"><p>keyYellow</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/ladder_mid.png"><p>ladder_mid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/ladder_top.png"><p>ladder_top</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/license.txt"><p>license</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidLava.png"><p>liquidLava</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidLavaTop.png"><p>liquidLavaT...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidLavaTop_mid.png"><p>liquidLavaT...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidWater.png"><p>liquidWater</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidWaterTop.png"><p>liquidWater...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/liquidWaterTop_mid.png"><p>liquidWater...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/lock_blue.png"><p>lock_blue</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/lock_green.png"><p>lock_green</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/lock_red.png"><p>lock_red</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/lock_yellow.png"><p>lock_yellow</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/mushroomBrown.png"><p>mushroomBro...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/mushroomRed.png"><p>mushroomRed</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/p1_front.png"><p>p1_front</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/p2_front.png"><p>p2_front</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/p3_front.png"><p>p3_front</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/particleBrick1a.png"><p>particleBri...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/particleBrick1b.png"><p>particleBri...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/particleBrick2a.png"><p>particleBri...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/particleBrick2b.png"><p>particleBri...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/plant.png"><p>plant</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/plantPurple.png"><p>plantPurple</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/pokerMad.png"><p>pokerMad</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/pokerSad.png"><p>pokerSad</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/rock.png"><p>rock</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/rockHillLeft.png"><p>rockHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/rockHillRight.png"><p>rockHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/ropeAttached.png"><p>ropeAttache...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/ropeHorizontal.png"><p>ropeHorizon...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/ropeVertical.png"><p>ropeVertica...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sand.png"><p>sand</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCenter.png"><p>sandCenter</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCenter_rounded.png"><p>sandCenter_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCliffLeft.png"><p>sandCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCliffLeftAlt.png"><p>sandCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCliffRight.png"><p>sandCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandCliffRightAlt.png"><p>sandCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHalf.png"><p>sandHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHalfLeft.png"><p>sandHalfLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHalfMid.png"><p>sandHalfMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHalfRight.png"><p>sandHalfRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHillLeft.png"><p>sandHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHillLeft2.png"><p>sandHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHillRight.png"><p>sandHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandHillRight2.png"><p>sandHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandLedgeLeft.png"><p>sandLedgeLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandLedgeRight.png"><p>sandLedgeRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandLeft.png"><p>sandLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandMid.png"><p>sandMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sandRight.png"><p>sandRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/sign.png"><p>sign</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/signExit.png"><p>signExit</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/signLeft.png"><p>signLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/signRight.png"><p>signRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/slime.png"><p>slime</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snail.png"><p>snail</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snailShell.png"><p>snailShell</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snow.png"><p>snow</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCenter.png"><p>snowCenter</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCenter_rounded.png"><p>snowCenter_...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCliffLeft.png"><p>snowCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCliffLeftAlt.png"><p>snowCliffLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCliffRight.png"><p>snowCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowCliffRightAlt.png"><p>snowCliffRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHalf.png"><p>snowHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHalfLeft.png"><p>snowHalfLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHalfMid.png"><p>snowHalfMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHalfRight.png"><p>snowHalfRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowhill.png"><p>snowhill</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHillLeft.png"><p>snowHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHillLeft2.png"><p>snowHillLef...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHillRight.png"><p>snowHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowHillRight2.png"><p>snowHillRig...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowLedgeLeft.png"><p>snowLedgeLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowLedgeRight.png"><p>snowLedgeRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowLeft.png"><p>snowLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowMid.png"><p>snowMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/snowRight.png"><p>snowRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/spikes.png"><p>spikes</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/springboardDown.png"><p>springboard...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/springboardUp.png"><p>springboard...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/star.png"><p>star</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stone.png"><p>stone</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCenter.png"><p>stoneCenter</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCenter_rounded.png"><p>stoneCenter...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCliffLeft.png"><p>stoneCliffL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCliffLeftAlt.png"><p>stoneCliffL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCliffRight.png"><p>stoneCliffR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneCliffRightAlt.png"><p>stoneCliffR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHalf.png"><p>stoneHalf</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHalfLeft.png"><p>stoneHalfLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHalfMid.png"><p>stoneHalfMi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHalfRight.png"><p>stoneHalfRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHillLeft2.png"><p>stoneHillLe...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneHillRight2.png"><p>stoneHillRi...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneLedgeLeft.png"><p>stoneLedgeL...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneLedgeRight.png"><p>stoneLedgeR...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneLeft.png"><p>stoneLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneMid.png"><p>stoneMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneRight.png"><p>stoneRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/stoneWall.png"><p>stoneWall</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/switchLeft.png"><p>switchLeft</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/switchMid.png"><p>switchMid</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/switchRight.png"><p>switchRight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/tochLit.png"><p>tochLit</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/tochLit2.png"><p>tochLit2</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/torch.png"><p>torch</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/weight.png"><p>weight</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/weightChained.png"><p>weightChain...</p></div>
<div class="img-holder"><img src="texture_packs/platformer_graphics_deluxe/window.png"><p>window</p></div>
`)